### ISSUE TITLE
Frontend Structure

### ISSUE THREAD

**Issue by jreitz-dev** [jreitz-dev/csgo-serverinfo#1]
Hey @Gomplimus ,

nice to see you getting started. But I've got a few questions regarding the frontend _structure_.

* Is it necessary to have a public folder inside the repo? This seems like something a build task would create
* Can we ignore compiled css? I mean you are clearly using some sort of node sass thingy 😕 
* Are you planing on doing frontend / component test?

**Comment by Gomplimus** [comment]
You were right with your note about the folder and the css. I've got a frontend test for the App.js that just tests wether it crashes at start or not. Currently im not planing in doing more tests for components.
